### ISSUE TITLE
std::bad_alloc during std::fill

### ISSUE THREAD

**Issue by ShelbyZ** [OguzDerin/cpp_std_for_each_speed_test#2]
While running through the speed_test, I'm encountering a failure on the 3rd loop iteration when running std::fill (~line42):

>Unhandled exception at 0x767108B2 in std_for_each_speed_test.exe: Microsoft C++ exception: >std::bad_alloc at memory location 0x008FFAF8.

After testing on two different machines, I get the same results:

- Machine A - 64GB/i7-6700k
- Machine B - 32GB/i7-3770

Not sure if there it is an missing command/configuration.

**Comment by OguzDerin** [comment]
On my machine, it was related to the memory limitations of 32-bit targets. I have added support for 32-bit targets by changing `int64_t` variables to use `int32_t` and reducing sum result to `536870908`.

Thanks for reporting the problem, could you reply after testing if the fix works for you?

Fix: 7474fd49d3e87439876c00984725cf1b4642451b

**Comment by ShelbyZ** [comment]
Yeah that did indeed work, I have a PR in mind for allowing larger sample sizes like the original.
