### ISSUE TITLE
Consider adding sections to README.md for Compiler Requirements

### ISSUE THREAD

**Issue by ShelbyZ** [OguzDerin/cpp_std_for_each_speed_test#3]
For MSVC it requires at least having:

![image](https://user-images.githubusercontent.com/1033099/33648442-bea70f4a-da0e-11e7-895d-ba4db220e647.png)

to get access to <execution>

**Comment by OguzDerin** [comment]
Added compiler requirements table with MSVC, GNU, Clang and Intel headers.
